name: Infracost

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required to post Infracost comments on PRs
      pull-requests: write

    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Infracost estimate
        run: |
          infracost breakdown --path . \
                              --format json \
                              --out-file /tmp/infracost.json

      - name: Post Infracost comment
        uses: infracost/actions/comment@v3
        with:
          path: /tmp/infracost.json
          # Updates the existing comment instead of creating a new one on every commit
          behavior: update
