name: Infracost

on:
  push:
    branches:
      - main

jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      INFRACOST_ENABLE_CLOUD: true

    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Infracost Scan
        run: |
          infracost scan --path .
