name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-ci:
    name: Terraform CI Pipeline
    runs-on: ubuntu-latest
    
    env:
      INFRACOST_ENABLE_CLOUD: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches (needed for Gitleaks)

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        
      - name: Run TFLint
        run: |
          tflint --init
          tflint -f compact
        working-directory: parent_module/dev
          
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: parent_module/dev
        
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          
      - name: Run Infracost Breakdown
        run: infracost breakdown --path parent_module/dev
        
      - name: Terraform Init
        run: terraform init
        working-directory: parent_module/dev
        
      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: parent_module/dev
        
      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: parent_module/dev
